baseURL = "https://uapi-group.org/docs"
languageCode = "en-us"
title = "UAPI group generic documents and meeting minutes"
theme = "hugo-book"

[[menu.before]]
  name = "⬅️  Back to top"
  url = "https://uapi-group.org/"
  weight = 1
[[menu.before]]
  name = "⸻"
  weight = 2

[[menu.after]]
  name = "⸻"
  weight = 10
[[menu.after]]
  name = "Collaborate on Github"
  url = "https://github.com/uapi-group/docs"
  weight = 11

[markup.goldmark.renderer]
  unsafe = true # Allow HTML in md files

[params]
  BookPortableLinks = true
  BookSection = '*'
  BookRepo = 'https://github.com/uapi-group/docs'
  BookCommitPath = 'commit'
  BookEditPath = 'edit/main'
  BookIndexPage = 'README.md'
