baseURL = "https://uapi-group.org/conferences"
languageCode = "en-us"
title = "Conferences and Minutes"
theme = "hugo-book"

[[menu.before]]
  name = "⬅️  Back to top"
  url = "/.."
  weight = 1

[[menu.after]]
  name = "Source repo for this page"
  url = "https://github.com/uapi-group/conferences"
  weight = 11

[markup.goldmark.renderer]
  unsafe = true # Allow HTML in md files

[params]
  BookPortableLinks = true
  BookSection = '*'
  BookRepo = 'https://github.com/uapi-group/conferences'
  BookCommitPath = 'commit'
  BookEditLink = '{{ .Site.Params.BookRepo }}/edit/main/{{ .Path }}'
  BookIndexPage = 'README.md'
  BookTheme = 'auto'

[modules]
  [[module.mounts]]
    source = '../README.md'
    target = 'content/_index.md'
  [[module.mounts]]
    source = '../conferences'
    target = 'content/conferences'
  [[module.mounts]]
    source = '../minutes'
    target = 'content/minutes'
